### PR TITLE
Implement no_std

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by Kijewski** [comment]
Before I work further on this PR, can you tell me if it is wanted at all? It works "mostly", except for the most important part: replacing [`SystemTime::now()`](https://doc.rust-lang.org/stable/std/time/struct.SystemTime.html#method.now). Rustix seems to work fine on Unices, but on windows [`clock_gettime()`](https://docs.rs/rustix/0.35.7/rustix/time/fn.clock_gettime.html) is not supported and I don't have high hopes that is ever will be. But I could experiment with [libc](https://crates.io/crates/libc), or even [winapi](https://crates.io/crates/winapi/).

**Comment by Kijewski** [comment]
Related issue https://github.com/Kijewski/tzdb/issues/71. Cc @[baoyachi](https://github.com/baoyachi).

**Comment by x-hgg-x** [comment]
We don't need to put `UtcDateTime::now()` and `DateTime::now()` in the `no-std` part, since they are simple wrappers of `UtcDateTime::from_timespec()` and `DateTime::from_timespec()`.

If the calling code want to get the current time, it can use whatever is available on the target platform and then call the `*::from_timespec()` methods.

**Comment by x-hgg-x** [comment]
Implemented in 3eae3eb.

**Pull request closed without merging**
